# Generated by Django 5.1 on 2025-12-08 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='ybodke123@gmail.com', max_length=50, validators=[django.core.validators.EmailValidator]),
            preserve_default=False,
        ),
    ]
